coverage:
  fixes:
    - "__init__.py::outleap/__init__.py"
  ignore:
    - "src/outleap/scripts"
  status:
    project:
      default:
        # Do not fail commits if the code coverage drops.
        target: 0%
        threshold: 100%
        base: auto
    patch:
      default:
        only_pulls: true
